#Made by RedBoy for ThunderLand
#    ____           ______  __
#   / __ )___  ____/ / __ \/ /___ _________    __
#  / __  / _ \/ __  / /_/ / / __ `/ ___/ _ \__/ /_
# / /_/ /  __/ /_/ / ____/ / /_/ / /__/  __/_  __/
#/_____/\___/\__,_/_/   /_/\__,_/\___/\___/ /_/

#Enable/Disable Plugin
enable: true

#Distance Check
distance-check: 1.2 #Blocks